POST http://localhost:3001/api/post/convertdate
Content-Type: application/json

{
    "date": "2020-01-05"
}
###

POST http://localhost:3001/api/auth/password-reset
Content-Type: application/json

{
    "email": "info@jewishbirthdaymakeover.com"
}

###

POST http://localhost:3001/api/auth/password-reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE2MzUzNzkxMjgsImV4cCI6MTYzNTQ2NTUyOH0.Ro661t1Mon3FVInZJue-NRJePwTyj6R1em-0QRQQFmg


###


GET  http://localhost:3001/api/auth/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxNSwiaWF0IjoxNjM1NjUwNzU1LCJleHAiOjE2MzU3MzcxNTV9.Vwmml6EI60J6PDaCxJ07GMRJ4OT9Tvc-xkjyPJzGcRU
###
GET http://localhost:8080/api/auth/password-reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MzU2NTAxNDMsImV4cCI6MTYzNTczNjU0M30.4Gg3dx329FOmBqYmC6gQ0mNG7UFLEu80A7rmwdk0Gv8

###
POST http://localhost:3001/api/auth/test
Content-Type: application/json

{
    
}
###
POST http://localhost:3001/api/auth/register/
Content-Type: application/json

{
    "user": {
        "firstname": "meedia",
        "lastname": "bloke",
        "email": "yyitzinger@gmail.com",
        "password": "password",
        "passwordRepeat": "password",
        "uploaderDOBEnglish": "2020-10-13",
        "uploaderDOBHebrew": "5773-12-11"
    }
}

###

POST http://localhost:3001/api/auth/login/
Content-Type: application/json

{
    "email": "yyitzinger@gmail.com",
    "password": "password"
}

###

POST http://localhost:3001/api/post/validatetoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInVwbG9hZGVyRmlyc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckxhc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckVtYWlsIjoibWVkaWFibG9rZWRlYWxzQGdtYWlsLmNvbSIsInVwbG9hZGVyUGFzc3dvcmQiOiIkMmIkMTAkcnlNLzRRMC5ZZ3NENFh3L3E0QjBQZTNnWDZyNm11NGJDcXlleUpxd0dkQlpLeHowUTRrenkiLCJ1cGxvYWRlckRPQkVuZ2xpc2giOiIyMDIxLTEwLTE5IiwidXBsb2FkZXJET0JIZWJyZXciOiIxMy1IZXNodmFuLTU3ODIiLCJpYXQiOjE2MzQ2OTQ4NTZ9.4hjMQHPRpsZG9WvFTASUqKjKqsFuOJP4h5lfw4VhaV0

{
    
}

###

GET http://localhost:3001/api/get/getuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInVwbG9hZGVyRmlyc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckxhc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckVtYWlsIjoibWVkaWFibG9rZWRlYWxzQGdtYWlsLmNvbSIsInVwbG9hZGVyUGFzc3dvcmQiOiIkMmIkMTAkcnlNLzRRMC5ZZ3NENFh3L3E0QjBQZTNnWDZyNm11NGJDcXlleUpxd0dkQlpLeHowUTRrenkiLCJ1cGxvYWRlckRPQkVuZ2xpc2giOiIyMDIxLTEwLTE5IiwidXBsb2FkZXJET0JIZWJyZXciOiIxMy1IZXNodmFuLTU3ODIiLCJpYXQiOjE2MzQ2OTQ4NTZ9.4hjMQHPRpsZG9WvFTASUqKjKqsFuOJP4h5lfw4VhaV0


###
POST http://localhost:3001/api/post/create-new-product
Content-Type: application/json

{

}
###
GET http://localhost:3000/getall/allvideos

###
POST http://localhost:3001/api/post/create-checkout-session
Content-Type: application/json

{
	"products": [{
			"adjustable_quantity": {
				"enabled": true,
				"minimum": 1,
				"maximum": 999
			},
			"price_data": {
                "currency": "usd",
                "unit_amount": 1000,
                "product_data": {
                    "name": "SampleVideo_1280x720_2mb.mp4"
                    }
                },
            
			"quantity": 1
		}
	]
}

###
GET http://api.mux.com/video/v1/assets/nK01Wb01xbu8TxyY3NFyPKG02qCta5np7PrRrVDuQkpee00
Authorization: Basic YmU2NDQyNmQtMjAzMC00ZmRjLTk1MDYtMWQwZWQwNGE3M2EzOmlMSVB6RDFxSUpoRW1UUzBFNHlGbVFkd3BJSEZ2T0ZLWjA0N2NRanlDcm1MaTNRcnFROG9WelA2ZHFsTXM1OXpJamcyTnpxZElZZg==
Content-Type: text/plain
###
POST http://localhost:3001/api/auth/password-reset
Content-Type: application/json

{
    "email": "yyitzingerrr@gmail.com"
}