POST http://localhost:3000/post/convertdate
Content-Type: application/json

{
    "date": "2020-01-05"
}

###

POST http://localhost:3000/auth/register/
Content-Type: application/json

{
    "user": {
        "firstname": "meedia",
        "lastname": "bloke",
        "email": "mediablokedeals2@gmail.com",
        "password": "password",
        "passwordRepeat": "password",
        "uploaderDOBEnglish": "2020-10-13",
        "uploaderDOBHebrew": "5773-12-11"
    }
}

###

POST http://localhost:3000/auth/login/
Content-Type: application/json

{
    "email": "mediablokedeals2@gmail.com",
    "password": "password"
}

###

POST http://localhost:3000/post/validatetoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsInVwbG9hZGVyRmlyc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckxhc3ROYW1lIjoiYWEiLCJ1cGxvYWRlckVtYWlsIjoibWVkaWFibG9rZWRlYWxzQGdtYWlsLmNvbSIsInVwbG9hZGVyUGFzc3dvcmQiOiIkMmIkMTAkcnlNLzRRMC5ZZ3NENFh3L3E0QjBQZTNnWDZyNm11NGJDcXlleUpxd0dkQlpLeHowUTRrenkiLCJ1cGxvYWRlckRPQkVuZ2xpc2giOiIyMDIxLTEwLTE5IiwidXBsb2FkZXJET0JIZWJyZXciOiIxMy1IZXNodmFuLTU3ODIiLCJpYXQiOjE2MzQ2OTQ4NTZ9.4hjMQHPRpsZG9WvFTASUqKjKqsFuOJP4h5lfw4VhaV0

{
    
}

###

DELETE http://localhost:3000/auth/logout/
Content-Type: application/json