POST http://localhost:3000/post/convertdate
Content-Type: application/json

{
    "date": "2020-01-05",
    "userIp": "192.168.1.1"
}

###


POST http://localhost:3000/auth/register/
Content-Type: application/json

{
    "firstname": "meedia",
    "lastname": "bloke",
    "email": "medbtee375@aol.com",
    "password": "password",
    "passwordRepeat": "password",
    "uploaderDOBEnglish": "2020-10-13",
    "uploaderDOBHebrew": "5773-12-11"
}

###

POST http://localhost:3000/auth/login/
Content-Type: application/json

{
    "email": "medbtee375@aol.com",
    "password": "password"
}